services:

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "7826567"
      POSTGRES_DB: demo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hermes_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d demo"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: "7826567"
      DB_NAME: demo
      DB_PORT: "5432"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - hermes_net
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  hermes_net:
    driver: bridge
